# Generated by Django 3.1.4 on 2020-12-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_moreprojectdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moreprojectdetails',
            old_name='title',
            new_name='project',
        ),
    ]
